---
# Stands up an ipsilon instance for simple SSO
- name: Configure koji hub and web server
  hosts: kojihub
  become: true
  vars_files:
    #- vars/vaults/encpass.yml
    - vars/common.yml
    - vars/production/kojid.yml
    - vars/production/koji-common.yml

  # This is to try to avoid the handler issue in pre/post tasks
  handlers:
    - ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: Check if ansible cannot be run here
      ansible.builtin.stat:
        path: /etc/no-ansible
      register: no_ansible

    - name: Verify if we can run ansible
      ansible.builtin.assert:
        that:
          - "not no_ansible.stat.exists"
        success_msg: "We are able to run on this node"
        fail_msg: "/etc/no-ansible exists - skipping run on this node"

    - name: Check for keytabs - kojid
      ansible.builtin.stat:
        path: /etc/kojid.keytab
      register: kojid_keytab_check
      changed_when: "1 != 1"

    - name: Verify keytab
      ansible.builtin.assert:
        that:
          - "kojid_keytab_check.stat.exists"
        success_msg: "It is likely we have all keytabs"
        fail_msg: "There are no keytabs. Please build the keytabs."

    # EPEL and PowerTools are required for ipsilon to function
    # I also couldn't find an ansible built-in to do this
    - name: Enable the PowerTools repository
      community.general.ini_file:
        dest: /etc/yum.repos.d/CentOS-Stream-PowerTools.repo
        section: powertools
        option: enabled
        value: 1
        owner: root
        group: root
        mode: '0644'
      when: ansible_distribution_major_version == '8'

    - name: Enable the CRB repository
      community.general.ini_file:
        dest: /etc/yum.repos.d/rocky.repo
        section: crb
        option: enabled
        value: 1
        owner: root
        group: root
        mode: '0644'
      when: ansible_distribution_major_version | int >= 9

    - name: Enable the EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present
      tags:
        - packages

    - name: Install rocky-tools copr
      ansible.builtin.yum_repository:
        name: copr:copr.fedorainfracloud.org:nalika:rockylinux-tool
        description: Copr repo for rockylinux-tools owned by nalika
        file: copr_repos
        baseurl: https://download.copr.fedorainfracloud.org/results/nalika/rockylinux-tools/epel-8-$basearch/
        gpgcheck: true
        gpgkey: https://download.copr.fedorainfracloud.org/results/nalika/rockylinux-tools/pubkey.gpg
        enabled: true
      when: ansible_distribution_major_version == '8'

  # Right now, we are not sure how or where we'll get our certificates. So we
  # are presenting a choice by setting a variable, koji_internal_ca. There is a
  # change that we will have to do internal certs for mqtt anyway.
  # TODO: We need an MQTT role and pre_tasks for the keytabs for this role
  roles:
    - role: oelabox.kojid
      state: present

  post_tasks:
    #- name: "Setup shared filesystem mount"
    #  ansible.builtin.import_tasks: tasks/koji_efs.yml

    - name: Touching run file that ansible has ran here
      file:
        path: /var/log/ansible.run
        state: touch
        mode: '0644'
        owner: root
        group: root
...
