---
- name: Create Koji services
  hosts: kojihub

  vars:
    ipa_admin: admin
    ipaadmin_password: freeloader
    services:
      - compile/koji.qslinux.com
      - HTTP/koji.qslinux.com
      - kojira/koji.qslinux.com
      - koji-gc/koji.qslinux.com

  tasks:
    - name: Create services
      include_tasks: tasks/oelabox-ipa/import-ipaservice.yml
      vars:
        ipa_service: "{{ item }}"
      loop: "{{ services }}"
