---
- name: Create Koji services
  hosts: kojihub

  vars:
    ipa_admin: admin
    ipaadmin_password: freeloader
    services:
      - compile/koji.oelabox.local
      - HTTP/koji.oelabox.local
      - kojira/koji.oelabox.local
      - koji-gc/koji.oelabox.local

  tasks:
    - name: Create services
      include_tasks: tasks/oelabox-ipa/import-ipaservice.yml
      vars:
        ipa_service: "{{ item }}"
      loop: "{{ services }}"
