---
- name: Configure Oela Box DNS Server
  hosts: dnsserver
  become: yes

  vars_files:
    - vars/oelabox-dns/common.yml

  handlers:
    - import_tasks: handlers/oelabox-dns/main.yml

  tasks:
    - import_tasks: tasks/oelabox-dns/server-setup.yml
