---
- name: Configure IPA client
  hosts: "{{ host | default(ipaclient) }}"
  become: true

  vars_files:
    - vars/oelabox-ipa/ipa/common.yml
    - vars/oelabox-ipa/ipa/ipaclient.yml

  pre_tasks:
    - name: Apply hostname based on inventory name
      hostname:
        name: "{{ inventory_hostname }}"
        use: systemd
      when: ansible_fqdn != inventory_hostname

  roles:
    - role: freeipa.ansible_freeipa.ipaclient
      state: present
