---
- name: Configure Oela Box DNS server
  hosts: dnsserver
  become: yes

  vars_files:
    - vars/common.yml

  handlers:
    - import_tasks: handlers/main.yml
    
  tasks:
    - import_tasks: tasks/server-setup.yml
