---
- name: Configure Oela Box DNS client.
  hosts: "{{ host | default(dnsclient) }}"
  become: true

    #vars_files:
    #- "{{ vars_file | default('vars/common.yml') }}"

  handlers:
    - import_tasks: handlers/main.yml

  tasks:
    - name: Use default resolv_entries
      ansible.builtin.include_vars:
        file: vars/common.yml
      when: resolv_entries is undefined

    - name: "Checking for user variables"
      ansible.builtin.assert:
        that:
          - resolv_entries | mandatory
        success_msg: "Required variables provided"
        fail_msg: "We are missing required information"

    - import_tasks: tasks/client-setup.yml
