---
- name: Install package dependencies
  ansible.builtin.dnf:
    name:
      - make
      - gcc
      - python3.11
      - python3.11-devel
      - python3.11-pip
      - krb5-devel

- name: Install pip dependencies
  ansible.builtin.pip:
    name:
      - pygithub
      - koji
    executable: pip3.11

- name: Create tools directory
  ansible.builtin.file:
    path: /home/vagrant/tools
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Install Oela Importer
  ansible.builtin.copy:
    src: tools/oelabox-koji/oelaimporter
    dest: /home/vagrant/tools
    owner: vagrant
    group: vagrant
    mode: '0644'

