---
# Currently only one SUDO role should be created, and that is for the
# Oela Box admins
- name: "Creating SUDO Role for Oela Box Admins"
  freeipa.ansible_freeipa.ipasudorule:
    ipaadmin_password: "{{ ipaadmin_password }}"
    name: All_OelaAdmins
    description: Oela Box infrastructure and operations sudo access
    group:
      - oelaadm
    hostcat: all
    cmdcat: all
...
