galaxy_info:
  author: Louis Abel
  description: Basic ipa-getcert role
  company: Rocky Linux Foundation
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - freeipa
dependencies: []
