---
# Handlers
- name: reload_networkmanager
  ansible.builtin.service:
    name: NetworkManager
    state: reloaded

- name: restart_named
  ansible.builtin.service:
    name: named
    state: restarted

- name: enable_firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true

- name: enable_crb
  ansible.builtin.shell: "set -o pipefail && /usr/bin/crb enable"
  changed_when: "1 != 1"

- name: enable_core_infra
  ansible.builtin.shell: "set -o pipefail && /usr/bin/dnf config-manager --enable core-infra"
  changed_when: "1 != 1"
...
